
Lmod is automatically replacing "cce/15.0.0" with "gcc/12.2.0".


Lmod is automatically replacing "PrgEnv-cray/8.3.3" with "PrgEnv-gnu/8.3.3".


Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.23     2) darshan-runtime/3.4.0

The following have been reloaded with a version change:
  1) rocm/5.4.0 => rocm/5.3.0

Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1650_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
    with open(sample_log_file) as f:
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1630_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1670_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1610_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton_prop.py", line 163, in <module>
    with open(sample_log_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/orion/proj-shared/nph159/data/64I/propagator/GSRC_Proton//sample_log/1710_W80_k3'
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 1476676.4 ON frontier05985 CANCELLED AT 2023-10-16T20:38:31 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 1476676.2 ON frontier02500 CANCELLED AT 2023-10-16T20:38:31 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 1476676.0 ON frontier01608 CANCELLED AT 2023-10-16T20:38:31 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 1476676 ON frontier01608 CANCELLED AT 2023-10-16T20:38:31 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 1476676.1 ON frontier01999 CANCELLED AT 2023-10-16T20:38:31 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 1476676.3 ON frontier04842 CANCELLED AT 2023-10-16T20:38:31 DUE TO TIME LIMIT ***
